# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_strand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_strand.proto',
  package='QuickBcc.Protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12proto_strand.proto\x12\x11QuickBcc.Protobuf\"\x82\x01\n\x0bInstruction\x12\r\n\x05index\x18\x01 \x01(\r\x12\x11\n\tstmt_type\x18\x02 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\x04\x12\x11\n\tfull_hash\x18\x04 \x01(\x0c\x12\x10\n\x08revision\x18? \x01(\r\x12\x0c\n\x04\x64\x65sc\x18@ \x01(\t\x12\x10\n\x08\x66ull_str\x18\x41 \x01(\t\"\xca\x01\n\x06Strand\x12\x0f\n\x07\x62\x62_addr\x18\x01 \x01(\x04\x12\x12\n\ninput_hash\x18\x02 \x01(\x0c\x12\x13\n\x0boutput_hash\x18\x03 \x01(\x0c\x12\x10\n\x08jumpkind\x18\x04 \x01(\r\x12-\n\x05insts\x18\x0f \x03(\x0b\x32\x1e.QuickBcc.Protobuf.Instruction\x12\x10\n\x08revision\x18? \x01(\r\x12\x0c\n\x04\x64\x65sc\x18@ \x01(\t\x12\x11\n\tinput_str\x18\x41 \x01(\t\x12\x12\n\noutput_str\x18\x42 \x01(\t\"\xc9\x01\n\x08\x46unction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\x04\x12\x0c\n\x04size\x18\x03 \x01(\x04\x12\x12\n\ncall_count\x18\x04 \x01(\x05\x12\x13\n\x0btext_offset\x18\x05 \x01(\x04\x12\x1a\n\x12total_strand_count\x18\x0e \x01(\x05\x12*\n\x07strands\x18\x0f \x03(\x0b\x32\x19.QuickBcc.Protobuf.Strand\x12\x10\n\x08\x62\x62_addrs\x18\x10 \x03(\x04\x12\x10\n\x08revision\x18? \x01(\r\"\x8e\x02\n\x06\x42inary\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x04\x12\x0b\n\x03md5\x18\x04 \x01(\x0c\x12\x0c\n\x04sha1\x18\x05 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x06 \x01(\x05\x12\x0c\n\x04\x61rch\x18\x07 \x01(\x05\x12\x0e\n\x06\x65ndian\x18\x08 \x01(\x05\x12\x0f\n\x07\x62itness\x18\t \x01(\x05\x12\x0b\n\x03tag\x18\x0e \x01(\t\x12.\n\tfunctions\x18\x0f \x03(\x0b\x32\x1b.QuickBcc.Protobuf.Function\x12\x13\n\x0btext_offset\x18\x11 \x01(\x04\x12\x11\n\ttext_size\x18\x12 \x01(\x04\x12\x10\n\x08revision\x18? \x01(\rb\x06proto3')
)




_INSTRUCTION = _descriptor.Descriptor(
  name='Instruction',
  full_name='QuickBcc.Protobuf.Instruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='QuickBcc.Protobuf.Instruction.index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stmt_type', full_name='QuickBcc.Protobuf.Instruction.stmt_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='QuickBcc.Protobuf.Instruction.addr', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_hash', full_name='QuickBcc.Protobuf.Instruction.full_hash', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='QuickBcc.Protobuf.Instruction.revision', index=4,
      number=63, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='QuickBcc.Protobuf.Instruction.desc', index=5,
      number=64, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_str', full_name='QuickBcc.Protobuf.Instruction.full_str', index=6,
      number=65, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=172,
)


_STRAND = _descriptor.Descriptor(
  name='Strand',
  full_name='QuickBcc.Protobuf.Strand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bb_addr', full_name='QuickBcc.Protobuf.Strand.bb_addr', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_hash', full_name='QuickBcc.Protobuf.Strand.input_hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_hash', full_name='QuickBcc.Protobuf.Strand.output_hash', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jumpkind', full_name='QuickBcc.Protobuf.Strand.jumpkind', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insts', full_name='QuickBcc.Protobuf.Strand.insts', index=4,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='QuickBcc.Protobuf.Strand.revision', index=5,
      number=63, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='QuickBcc.Protobuf.Strand.desc', index=6,
      number=64, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_str', full_name='QuickBcc.Protobuf.Strand.input_str', index=7,
      number=65, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_str', full_name='QuickBcc.Protobuf.Strand.output_str', index=8,
      number=66, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=377,
)


_FUNCTION = _descriptor.Descriptor(
  name='Function',
  full_name='QuickBcc.Protobuf.Function',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='QuickBcc.Protobuf.Function.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='QuickBcc.Protobuf.Function.addr', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='QuickBcc.Protobuf.Function.size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_count', full_name='QuickBcc.Protobuf.Function.call_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_offset', full_name='QuickBcc.Protobuf.Function.text_offset', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_strand_count', full_name='QuickBcc.Protobuf.Function.total_strand_count', index=5,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strands', full_name='QuickBcc.Protobuf.Function.strands', index=6,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bb_addrs', full_name='QuickBcc.Protobuf.Function.bb_addrs', index=7,
      number=16, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='QuickBcc.Protobuf.Function.revision', index=8,
      number=63, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=581,
)


_BINARY = _descriptor.Descriptor(
  name='Binary',
  full_name='QuickBcc.Protobuf.Binary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='QuickBcc.Protobuf.Binary.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='QuickBcc.Protobuf.Binary.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_size', full_name='QuickBcc.Protobuf.Binary.file_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='md5', full_name='QuickBcc.Protobuf.Binary.md5', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sha1', full_name='QuickBcc.Protobuf.Binary.sha1', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='QuickBcc.Protobuf.Binary.format', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arch', full_name='QuickBcc.Protobuf.Binary.arch', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endian', full_name='QuickBcc.Protobuf.Binary.endian', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bitness', full_name='QuickBcc.Protobuf.Binary.bitness', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='QuickBcc.Protobuf.Binary.tag', index=9,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='functions', full_name='QuickBcc.Protobuf.Binary.functions', index=10,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_offset', full_name='QuickBcc.Protobuf.Binary.text_offset', index=11,
      number=17, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_size', full_name='QuickBcc.Protobuf.Binary.text_size', index=12,
      number=18, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='QuickBcc.Protobuf.Binary.revision', index=13,
      number=63, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=854,
)

_STRAND.fields_by_name['insts'].message_type = _INSTRUCTION
_FUNCTION.fields_by_name['strands'].message_type = _STRAND
_BINARY.fields_by_name['functions'].message_type = _FUNCTION
DESCRIPTOR.message_types_by_name['Instruction'] = _INSTRUCTION
DESCRIPTOR.message_types_by_name['Strand'] = _STRAND
DESCRIPTOR.message_types_by_name['Function'] = _FUNCTION
DESCRIPTOR.message_types_by_name['Binary'] = _BINARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Instruction = _reflection.GeneratedProtocolMessageType('Instruction', (_message.Message,), dict(
  DESCRIPTOR = _INSTRUCTION,
  __module__ = 'proto_strand_pb2'
  # @@protoc_insertion_point(class_scope:QuickBcc.Protobuf.Instruction)
  ))
_sym_db.RegisterMessage(Instruction)

Strand = _reflection.GeneratedProtocolMessageType('Strand', (_message.Message,), dict(
  DESCRIPTOR = _STRAND,
  __module__ = 'proto_strand_pb2'
  # @@protoc_insertion_point(class_scope:QuickBcc.Protobuf.Strand)
  ))
_sym_db.RegisterMessage(Strand)

Function = _reflection.GeneratedProtocolMessageType('Function', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTION,
  __module__ = 'proto_strand_pb2'
  # @@protoc_insertion_point(class_scope:QuickBcc.Protobuf.Function)
  ))
_sym_db.RegisterMessage(Function)

Binary = _reflection.GeneratedProtocolMessageType('Binary', (_message.Message,), dict(
  DESCRIPTOR = _BINARY,
  __module__ = 'proto_strand_pb2'
  # @@protoc_insertion_point(class_scope:QuickBcc.Protobuf.Binary)
  ))
_sym_db.RegisterMessage(Binary)


# @@protoc_insertion_point(module_scope)
